import type { Metadata } from "next";
import "./globals.css"
import localFont from "next/font/local";

const switzer = localFont({
  src: [
    {
      path: "../../assets/fonts/Switzer/Switzer-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Extralight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../assets/fonts/Switzer/Switzer-Thin.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-switzer",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} bg-background antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
